### ISSUE TITLE
Pinch to zoom gesture not working on Android when used inside ScrollView

### ISSUE THREAD

**Issue by christianrank** [vemarav/react-native-avatar-crop#12]
**Describe the bug**
When the Crop component is used inside of a ScrollView, the image can't be zoomed with 2 fingers on Android, instead the ScrollView is moving. Just moving the image with 1 finger works fine.

On iOS, everything works as expected.

**To Reproduce**
1. Put the `<Crop>` inside a `<ScrollView>`
2. Try to zoom the image with 2 fingers on Android
3. The screen is scrolling

**Expected behavior**
Pinch to zoom should work on Android also when used inside a ScrollView.

**Smartphone:**
 - OS: Android (tested with 7 and 11)

**Additional context**
Might be related: https://github.com/software-mansion/react-native-gesture-handler/issues/1082

**Comment by vemarav** [comment]
change
`import { ScrollView } from 'react-native';`
to
`import { ScrollView } from 'react-native-gesture-handler';`

**Comment by christianrank** [comment]
I tried that already, it didn't work.

(tried with `react-native-gesture-handler` versions `1.10.3` and `2.1.0`)

**Comment by vemarav** [comment]
Try following scrollview props, if it still doesn't work please create a reproducible repo

```jsx
//...
import { ScrollView } from 'react-native';

//...
<ScrollView 
disableScrollViewPanResponder={true}
nestedScrollEnabled={true}
pinchGestureEnabled={false}
>
<Crop>
//...
</ScrollView>

```

**Comment by christianrank** [comment]
Thanks, I also didn't have luck with that.

I'm currently trying to setup a reproduction repo, but with a fresh project I can't get any gestures working on Android, even without using a ScrollView on this screen I can't move the image now. It's working fine on iOS.

So this repo isn't showing the bug yet, but something else is already broken.

I'm giving up for today, but maybe you have an idea?

https://github.com/christianrank/react-native-avatar-crop-bug-reproduction

**Comment by vemarav** [comment]
The example already uses a scrollview and it works,
https://github.com/vemarav/react-native-avatar-crop/blob/d0910826126869e22d82aa2d8acc0762df1a1fe9/example/CropImage.tsx#L46

use [react-native-gesture-handler@1.10.3](https://www.npmjs.com/package/react-native-gesture-handler/v/1.10.3)

WIP to support react-native-gesture-handler v2

**Comment by nitin41** [comment]
Please check #14 for the solution.

**Comment by marksyzm** [comment]
@vemarav 
Which branch is this support work being done on? Keen to see it!
