### ISSUE TITLE
MaskedView can't be used anywhere else in the project

### ISSUE THREAD

**Issue by christianrank** [vemarav/react-native-avatar-crop#13]
**Describe the bug**
This package already registers RNCMaskedView, so it can't be used anywhere else. This shouldn't be the case. Instead it should use the MaskedView component from that package.

**To Reproduce**
1. Use this package
2. Import MaskedView somewhere else in your project and use it
```js
import MaskedView from '@react-native-masked-view/masked-view'
// ...
<MaskedView />
```
3. Get this error: `Invariant Violation: Tried to register two views with the same name RNCMaskedView`

**Expected behavior**
MaskedView should be usable somewhere else.

**Smartphone:**
- iOS and Android

**Comment by vemarav** [comment]
fixed https://github.com/vemarav/react-native-avatar-crop/commit/491d85b4c57b52ed2785b81cdb28844cfa8e440d, use react-native-avatar-crop v1.3.4
