### ISSUE TITLE
Tried to register two views with the same name RNCMaskedView

### ISSUE THREAD

**Issue by pacosta613** [vemarav/react-native-avatar-crop#15]
I am getting this error when I used this module. any ideas as to why?

**Comment by vemarav** [comment]
I think you are using https://www.npmjs.com/package/@react-native-community/masked-view(deprecated) instead of https://www.npmjs.com/package/@react-native-masked-view/masked-view

**Comment by pacosta613** [comment]
It's possible the react-native community/masked-view can be causing this issue but I need it for react-navigation.

**Comment by vemarav** [comment]
use v1.2.4,

npm
```
npm install --save react-native-avatar-crop@1.2.4
```

yarn
```
yarn add react-native-avatar-crop@1.2.4
```

**Comment by pacosta613** [comment]
thanks this work but we got another issue now.
