### ISSUE TITLE
RNCMaskedView was not found in UIManager

### ISSUE THREAD

**Issue by pacosta613** [vemarav/react-native-avatar-crop#16]
RNCMaskedView was not found in UIManager.

![Screen Shot 2022-02-10 at 11 42 41 AM](https://user-images.githubusercontent.com/15216315/153454550-ab40ba07-742d-4bd3-8e1e-b625dda1cb5e.png)
r

**Comment by vemarav** [comment]
try v1.2.3 or v1.1.1

**Comment by pacosta613** [comment]
neither works

**Comment by vemarav** [comment]
need a reproducible repo

**Comment by victorglomer** [comment]
react-native run-ios solved for me
just a rebuild

**Comment by satyabrata-dash5** [comment]
issue coming with me after updating android studio

**Comment by CatalinTudose** [comment]
any news on this?
