### ISSUE TITLE
Using http url in source uri crashes the app

### ISSUE THREAD

**Issue by himanshi7046** [vemarav/react-native-avatar-crop#2]

**Comment by vemarav** [comment]
can you provide a reproducible code or share uri format

**Comment by himanshi7046** [comment]
<Crop
                    source={{ uri: 'http://picsum.photos/200/100' }}
                    width={SCREEN_WIDTH}
                    height={SCREEN_WIDTH}
                    cropArea={{ width: SCREEN_WIDTH / 1.3, height: SCREEN_WIDTH / 1.3 }}
                    onCrop={(cropCallback) => (crop = cropCallback)}
                />

**Comment by vemarav** [comment]
It doesn't support remote urls yet. you can download remote image and store in cache and pass the cached file uri to crop.
Also try with https

**Comment by himanshi7046** [comment]
Is there any example to do that way

**Comment by vemarav** [comment]
hey @himanshi7046,

the issue you are facing is because of `http`, the following snippet works. make sure you set allow insecure url config in your android manifest.

```
<Crop
        source={{
          uri: 'https://images.unsplash.com/photo-1627942152443-2c0defc72bb5?ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
        }}
        width={SCREEN_WIDTH}
        height={SCREEN_WIDTH}
        cropArea={{width: SCREEN_WIDTH / 1.3, height: SCREEN_WIDTH / 1.3}}
        onCrop={cropCallback => (crop = cropCallback)}
      />
```

**Comment by himanshi7046** [comment]
Null is not an object( evaluting 'RNImageSize.getSize') error

and added
android:usesCleartextTraffic="true"
in android manifest

**Comment by vemarav** [comment]
@himanshi7046  you are using redirected url, it won't work. you need to use the final url.

I got following image url by visiting the url you mentioned and it works.
https://i.picsum.photos/id/652/200/100.jpg?hmac=FHOGj_uJexMz6mmMNShTa6x_T5-flvAs--cj5Ip0sTU

**Comment by himanshi7046** [comment]
> @himanshi7046 you are using redirected url, it won't work. you need to use the final url.
> 
> I got following image url by visiting the url you mentioned and it works.
> https://i.picsum.photos/id/652/200/100.jpg?hmac=FHOGj_uJexMz6mmMNShTa6x_T5-flvAs--cj5Ip0sTU

Still having the same issue can you please check it before reply

**Comment by vemarav** [comment]
make a reproducible repo, I will check it out

**Comment by vemarav** [comment]
@himanshi7046 need more info to know why its crashing. without reproducible repo or crash logs I won't be able to help.

are you using npm@7 then check issue #3.

Happy to help resolve your issue. It is fully compatible with remote images.
