### ISSUE TITLE
Works on iOS, null is not an object(evaluating 'RNImageSize.getSize') on android

### ISSUE THREAD

**Issue by minuitagency** [vemarav/react-native-avatar-crop#7]
Hi, 

We use a very classic implementation: 

` <Crop
              cropShape={'rect'}
              source={{uri: picturePath}}
              width={'100%'}
              height={responsiveHeight(40)}
              cropArea={{
                width: CROPPING_ZONE,
                height: CROPPING_ZONE * aspectRatio,
              }}
              onCrop={cropCallback => (crop = cropCallback)}
            />`

Installed the library from the git you mentioned: 

![image](https://user-images.githubusercontent.com/38316888/139913203-0ef7494d-619b-4d31-b04f-45aae45adb56.png)

Everything works perfectly on iOS but on android we get the following error: 

`null is not an object(evaluating 'RNImageSize.getSize') `

Any idea? 

Thanks again for the great library, you were able to solve for us an important feature of our app. 

Théo

**Comment by vemarav** [comment]
@minuitagency can you create a reproducible public repo and tag me so that I can check

**Comment by minuitagency** [comment]
Hi @vemarav thanks so much for your help, here's the source code of the project: 

https://github.com/minuitagency/reproCropper

Thanks, 

Théo

**Comment by vemarav** [comment]
@minuitagency `yarn add react-native-image-size` or  `npm install react-native-image-size` will fix the issue. I have created a PR here https://github.com/minuitagency/reproCropper/pull/1/files
