### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCMaskedView

### ISSUE THREAD

**Issue by kamui545** [vemarav/react-native-avatar-crop#8]
**Describe the bug**

When including this library into my project I have the following error:

```
Invariant Violation: Tried to register two views with the same name RNCMaskedView.
```

**To Reproduce**

```
npm install @react-native-masked-view/masked-view
npm install react-native-avatar-crop
```

**Expected behavior**

Not having conflicts with new library.

---

I believe this error is due to the conflict between:
- `react-native-community/masked-view`
- `react-native-masked-view/masked-view`

They are both the same library but it was renamed and moved to its own organization as `react-native-masked-view/masked-view`, which is now the updated version.

I would suggest using `react-native-masked-view/masked-view` instead and releasing a new major version of your package to avoid breaking existing apps.

See:

- https://www.npmjs.com/package/@react-native-masked-view/masked-view
- https://www.npmjs.com/package/@react-native-community/masked-view

PR open: https://github.com/vemarav/react-native-avatar-crop/pull/9

**Comment by vemarav** [comment]
fixed 7ee33c166b1850cd9a85269a71c8b96fed2b5fb5
